add ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,6 +1,6 @@
 name: CI
 on:
-  pull_request_target:
+  pull_request: # TODO
   push:
     branches:
       - main
@@ -29,13 +29,105 @@ jobs:
           path: packages/python/.venv
           key: venv-${{ hashFiles('packages/python/poetry.lock') }}
       - run: make install
+      - run: make build
       - run: make check-format
       - run: make test-unit
       - if: failure() && runner.debug == '1'
         uses: mxschmitt/action-tmate@v3
 
-  examples:
-    name: Examples
+  # examples:
+  #   name: Examples
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 60
+  #   env:
+  #     ALUMNIUM_DRIVER: ${{ matrix.driver }}
+  #     ALUMNIUM_MODEL: ${{ matrix.model }}
+  #     ALUMNIUM_LOG_LEVEL: debug
+  #     ALUMNIUM_LOG_PATH: alumnium.log
+  #     ALUMNIUM_PLAYWRIGHT_HEADLESS: false
+  #     DISPLAY: :99
+  #     LT_USERNAME: ${{ secrets.LT_USERNAME }}
+  #     LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
+  #     ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
+  #     AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
+  #     AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
+  #     AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
+  #     AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
+  #     AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
+  #     DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
+  #     GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
+  #     MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
+  #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
+  #   defaults:
+  #     run:
+  #       working-directory: packages/python
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       driver:
+  #         - appium
+  #         - playwright
+  #         - selenium
+  #       model:
+  #         - anthropic
+  #         - aws_anthropic
+  #         - aws_meta
+  #         - azure_openai
+  #         # Official DeepSeek platform times out!
+  #         # - deepseek
+  #         - google
+  #         - mistralai
+  #         - openai
+  #   steps:
+  #     - id: check-access
+  #       uses: actions-cool/check-user-permission@v2
+  #       with:
+  #         require: write
+  #         username: ${{ github.triggering_actor }}
+  #     - if: steps.check-access.outputs.require-result == 'false'
+  #       run: |
+  #         echo "${{ github.triggering_actor }} does not have permissions on this repo - maintainer will re-run this job."
+  #         echo "Current permission level is ${{ steps.check-access.outputs.user-permission }}."
+  #         echo "Job originally triggered by ${{ github.actor }}."
+  #         exit 1
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
+  #     - uses: actions/setup-python@v5
+  #       with:
+  #         python-version-file: .tool-versions
+  #     - run: pip install poetry==$(cat .tool-versions | grep poetry | cut -d" " -f2)
+  #       working-directory: .
+  #     - uses: actions/cache@v4
+  #       with:
+  #         path: packages/python/.venv
+  #         key: venv-${{ hashFiles('packages/python/poetry.lock') }}
+  #     - run: poetry install
+  #     - if: matrix.driver == 'playwright'
+  #       run: poetry run playwright install chromium
+  #     - if: matrix.driver != 'appium'
+  #       run: Xvfb ${{ env.DISPLAY }} -screen 0 1600x1200x24 &
+  #     - uses: actions/cache@v4
+  #       with:
+  #         path: |
+  #           packages/python/.alumnium-cache.sqlite
+  #           packages/python/.alumnium/cache/
+  #         key: alumnium-cache-python-${{ matrix.driver }}-${{ matrix.model }}-${{ github.sha }}
+  #         restore-keys: alumnium-cache-python-${{ matrix.driver }}-${{ matrix.model }}-
+  #     - run: poetry run behave --format html-pretty --outfile reports/behave.html --format pretty ${{ matrix.driver == 'appium' && '--tags ~@web' || '' }}
+  #     - run: poetry run pytest --retries 1 --html reports/pytest.html examples/
+  #     - if: failure() && runner.debug == '1'
+  #       uses: mxschmitt/action-tmate@v3
+  #     - if: always()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: ${{ matrix.driver }}-${{ matrix.model }}
+  #         path: |
+  #           packages/python/*.log
+  #           packages/python/reports/
+
+  examples-ts:
+    name: packages/typescript / Examples
     runs-on: ubuntu-latest
     timeout-minutes: 60
     env:
@@ -59,14 +151,14 @@ jobs:
       OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
     defaults:
       run:
-        working-directory: packages/python
+        working-directory: packages/typescript
     strategy:
       fail-fast: false
       matrix:
         driver:
-          - appium
+          - mocha
           - playwright
-          - selenium
+          - wdio
         model:
           - anthropic
           - aws_anthropic
@@ -92,29 +184,24 @@ jobs:
       - uses: actions/checkout@v4
         with:
           ref: ${{ github.event.pull_request.head.sha || github.sha }}
-      - uses: actions/setup-python@v5
+      - uses: actions/setup-node@v4
         with:
-          python-version-file: .tool-versions
-      - run: pip install poetry==$(cat .tool-versions | grep poetry | cut -d" " -f2)
-        working-directory: .
-      - uses: actions/cache@v4
-        with:
-          path: packages/python/.venv
-          key: venv-${{ hashFiles('packages/python/poetry.lock') }}
-      - run: poetry install
+          cache: npm
+          node-version-file: .tool-versions
       - if: matrix.driver == 'playwright'
-        run: poetry run playwright install chromium
+        run: npx playwright install chromium
       - if: matrix.driver != 'appium'
         run: Xvfb ${{ env.DISPLAY }} -screen 0 1600x1200x24 &
+      - run: make start-server-docker
       - uses: actions/cache@v4
         with:
           path: |
-            packages/python/.alumnium-cache.sqlite
-            packages/python/.alumnium/cache/
-          key: alumnium-cache-python-${{ matrix.driver }}-${{ matrix.model }}-${{ github.sha }}
-          restore-keys: alumnium-cache-python-${{ matrix.driver }}-${{ matrix.model }}-
-      - run: poetry run behave --format html-pretty --outfile reports/behave.html --format pretty ${{ matrix.driver == 'appium' && '--tags ~@web' || '' }}
-      - run: poetry run pytest --retries 1 --html reports/pytest.html examples/
+            .alumnium-cache.sqlite
+            .alumnium/cache/
+          key: alumnium-cache-typescript-${{ matrix.driver }}-${{ matrix.model }}-${{ github.sha }}
+          restore-keys: alumnium-cache-typescript-${{ matrix.driver }}-${{ matrix.model }}-
+      - run: npm run examples:${{ matrix.driver }}
+        working-directory: packages/typescript
       - if: failure() && runner.debug == '1'
         uses: mxschmitt/action-tmate@v3
       - if: always()
@@ -122,17 +209,18 @@ jobs:
         with:
           name: ${{ matrix.driver }}-${{ matrix.model }}
           path: |
-            packages/python/*.log
-            packages/python/reports/
+            packages/typescript/*.log
+            packages/typescript/playwright-report/
+            packages/typescript/test-results/
 
-  release:
-    name: Release
-    needs:
-      - test
-      - examples
-    if: github.ref_name == 'main' && startsWith(github.event.head_commit.message, 'release:')
-    uses: ./.github/workflows/release.yml
-    permissions:
-      attestations: write
-      contents: write
-      id-token: write
+  # release:
+  #   name: Release
+  #   needs:
+  #     - test
+  #     - examples
+  #   if: github.ref_name == 'main' && startsWith(github.event.head_commit.message, 'release:')
+  #   uses: ./.github/workflows/release.yml
+  #   permissions:
+  #     attestations: write
+  #     contents: write
+  #     id-token: write
